@startuml overview
allowmixing
skinparam defaultFontName "Calibri"
skinparam classFontName "Calibri"
skinparam packageFontName "Calibri"
skinparam noteFontName "Calibri"
skinparam titleFontName "Calibri"
skinparam defaultFontSize 40
skinparam titleFontSize 28
skinparam backgroundColor #FFFFFF
skinparam packageBorderColor #444
skinparam packageBackgroundColor #FFFFFF
skinparam classBackgroundColor #F8F8F8
skinparam classBorderColor #888
skinparam classFontColor #222
skinparam nodesep 60
skinparam ranksep 60
skinparam shadowing false
skinparam roundcorner 8
skinparam defaultTextAlignment left
skinparam titleFontColor #222
skinparam noteBackgroundColor #F8F8F8
skinparam noteBorderColor #444

' Agrupar l10n y common
package "l10n" <<Rectangle>> #F4F4F4 {
  class app_es_arb
  class app_en_arb
}

' Paquetes funcionales principales
package "chat" <<Rectangle>> #FFFFFF {
    package "chat.data"
    package "chat.domain"
    package "chat.presentation"
}
package "auth" <<Rectangle>> #FFFFFF {
    package "auth.data"
    package "auth.domain"
    package "auth.presentation"
}
package "calendar" <<Rectangle>> #FFFFFF {
    package "calendar.data"
    package "calendar.domain"
    package "calendar.presentation"
}

package "common" <<Rectangle>> #F4F4F4 {
    package "animations"
    package "constants"
    package "theme"
    package "utils"
}
' Agrupar di y FirebaseOptions
package "di" <<Rectangle>> #F4F4F4 {
    class ServiceLocator
}
class FirebaseOptions
class Main

' Forzar disposición horizontal de los grupos
l10n -[hidden]-> common
chat -[hidden]-> auth
auth -[hidden]-> calendar
di -[hidden]-> FirebaseOptions

' Conexiones principales
Main --> l10n
Main --> FirebaseOptions
Main --> common
Main --> auth
Main --> calendar
Main --> chat
Main --> di

chat --> common
auth --> common
calendar --> common

@enduml

