name: eventify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  intl: ^0.19.0
  collection: ^1.19.1
  provider: ^6.1.1
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  http: ^1.1.0
  tflite_flutter: ^0.11.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_dark_no_background.png"